### ISSUE TITLE
Lock down version numbers in dependencies

### ISSUE THREAD

**Issue by morsssss** [ampproject/samples#105]
@rsimha , liked your idea of locking down versions so that people don't have trouble installing and building this project, as @danielrozenberg and @dvoytenko did.  Or of migrating from npm to yarn.  Can you advise here?

**Comment by rsimha** [comment]
Just saw this old issue during a long overdue triage. All ampproject repos have `renovate` enabled today to lock down dependencies and keep them up to date, so this problem should be solved.
