### ISSUE TITLE
Creating a PWAMP application using wordpress as CMS

### ISSUE THREAD

**Issue by Amanrazdan** [ampproject/samples#224]
Our team is trying to build a lite app using PWA + AMP (PWAMP as you call it ). We were actually very convinced with the approach that was implemented in https://amp.cards. However, we want to do the same using the WordPress CMS. I have been Scratching my head for days and come with the following approach that is actually what PWAMP is band rather using WordPress as CMS 
![image](https://user-images.githubusercontent.com/28403318/59501173-99fafc00-8eb8-11e9-9fd8-823cf97ec6ac.png)
Now the first part is relatively easy using amp plugin provided by amp contributors. And even using PWA plugin that creates the app. Now we are facing the following dilemma -
1. Styling that the CMS was using before was using ELEMENTOR which we think doesn't support AMP for now and shows a lot of validation errors 
2. Theme Supported by amp currently, we couldn't find one that can have news card like structure like the one you had an amp.cards project 
3. We still don't understand how to implement a shadow reader for PWA in WordPress even with the only plugin that exists in the store https://wordpress.org/plugins/pwamp/

I have done a lot of research and still, am confused with what to do. 

Could please refer any sample project like this that exist or from where to learn from. And also another relevant git repo's related to this issue.

**Comment by westonruter** [comment]
Cross posted from https://github.com/ampproject/amp-wp/issues/2628

**Comment by westonruter** [comment]
I've replied at https://github.com/ampproject/amp-wp/issues/2628#issuecomment-502409718

**Comment by Amanrazdan** [comment]
Yup thanks @westonruter

**Comment by westonruter** [comment]
This can be closed.

**Comment by Amanrazdan** [comment]
Following https://github.com/ampproject/amp-wp/issues/2628 from now
