### ISSUE TITLE
I tried to find the declaration the ${ampjs} but I did not find it. ¿Where is it?

### ISSUE THREAD

**Issue by CarlosMGomez** [ampproject/samples#273]
At the amp-camp project, in partials/head.html is declared this variable, but i was no able to find any reference about it. 

Many thanks for your help.

**Comment by morsssss** [comment]
Wow! @CarlosMGomez , thanks for finding this.

I'm pretty sure `${ampjs}` is an artifact of an earlier version of this project - when we generated all the `<script>` tags with an autogeneration module that's now been replaced by [amp-optimizer](https://github.com/ampproject/amp-toolbox/tree/master/packages/optimizer).

I've just removed this in my local build, and everything still worked. I'll take it out of this repo.

Let me know if you have any other questions about this project!
