### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/samples#285]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by morsssss** [comment]
Thanks for creating this issue, @rsimha ! One of us will take care of it....

**Comment by rsimha** [comment]
@morsssss I just checked and noticed that this repo contains no hard-coded references to the default branch. Happy to do the renaming for you if you'd like.

**Comment by morsssss** [comment]
Oh, thanks! That was going to be my first step: a big grep.

Please feel free to rename this - or to wait for me to do it next week :)

**Comment by rsimha** [comment]
No hurry, next week is good. Will leave this to you. 👍

**Comment by morsssss** [comment]
It's next week, and I'm now taking a look at this!

Unfortunately I think I lack the permissions to change the default branch. [Looks like](https://docs.github.com/en/github/administering-a-repository/changing-the-default-branch) I'd do this under the "Settings" menu - which doesn't appear for me.

![image](https://user-images.githubusercontent.com/29419498/116310692-55a93a00-a778-11eb-9962-481dad4ef8af.png)

Is that right? If so, do you have the power to grant me the privileges I'd need?

In any case I was proud to notice that I was the person with the most commits in this subrepo! (Though not, I will note, the most lines of code.)

**Comment by rsimha** [comment]
It's possible you need repo-wide admin access for this. I'm not sure who normally grants this, but I just took care of the branch renaming.

![image](https://user-images.githubusercontent.com/26553114/116311671-8473e000-a779-11eb-8284-09ae80a3f552.png)

Looks like there's no other CI config to update, so I think this issue can be closed.

**Comment by morsssss** [comment]
Thanks! That was quick ⚡️⚡️⚡️
