### ISSUE TITLE
amp-pwa is outdated

### ISSUE THREAD

**Issue by juangabrielr4** [ampproject/samples#84]
apm-pwa is not the latest version of [amp-pwa](https://github.com/choumx/amp-pwa)

**Comment by bpaduch** [comment]
@choumx - can you look at this?

**Comment by prasannamestha** [comment]
https://ampbench.appspot.com/validate_ua_desktop?url=https%3A%2F%2Fchoumx.github.io%2Famp-pwa%2F%23

You can see it fails the tests
